<?php
include('Controller.class');
include('Error.class');
require_once('Twig/Autoloader.php');
/*
	AUTHOR: Harmster
	WEBSITE: hawiak.nl
	DATE_MODIFIED: 11/22/2013 (DD/MM/YYYY)
*/
class MvcModule extends Process implements Module, ConfigurableModule {
	const PAGE_NAME = 'mvc-module';
	const PERMISSION_NAME = 'mvc-module';
	public $action = "";
	public $error = "";
	public static function getModuleInfo(){
		return array(
			'title' => 'MVC',
			'summary' => __('Module that enables MVC like programming'),
			'autoload' => true,
			'version' => 0.24,
			'author' => 'Harmster',
			'href' => '<Check later>'
		);
	}
	public function init(){
		Wire::setFuel('mvc', $this);
		Twig_Autoloader::register();
		$this->set('table', false); 
        $this->set('thead', ''); 
        $this->set('optionColumns', 0);
        $this->addHookAfter('TemplateFile::render', $this, 'create_mvc');
        //config propertys
        $this->snippets_path = $this->get('snippets_path');
        $this->controllers_path = $this->get('controllers_path');
        $this->default_layout = $this->get('default_layout');
        $this->layouts_path = $this->get('layouts_path');
        $this->views_path = $this->get('views_path');
        $this->app_controller_path = $this->get('app_controller_path');
        if($this->app_controller_path == "")
        	$app_controller = $this->config->paths->root . $this->app_controller_path . 'site/templates/AppController.class';
        else
        	$app_controller = $this->config->paths->root . $this->app_controller_path . '/AppController.class';
		include($app_controller);
		$this->error = new MvcError();
	}

	static public function getModuleConfigInputfields(array $data){
		//Controller root
		//Views root
		//Default layout
		//Layout folder
		$form = new InputfieldForm();
		$form->attr('id', 'mvc-config');
		$wrapper = new InputfieldWrapper();
		$wrapper->label = "Configure Layouts";
		$field = new InputfieldText();
		$field->label = 'Default layout file (php file in your layouts folder)';
		$field->attr('name+id', 'default_layout');
		if(isset($data['default_layout']) ? $field->value = $data['default_layout'] : $field->value = "layout.php");
		$wrapper->append($field);
		$field = new InputfieldText();
		$field->label = 'App Controller folder, where is the App Controller located';
		$field->attr('name+id', 'app_controller_path');
		if(isset($data['app_controller_path']) ? $field->value = $data['app_controller_path'] : $field->value = "/site/templates");
		$wrapper->append($field);
		$form->append($wrapper);
		$wrapper = new InputfieldWrapper();
		$wrapper->label = "Configure file locations";
		$field = new InputfieldText();
		$field->label = "Layouts path";
		$field->attr('name+id', 'layouts_path');
		if(isset($data['layouts_path']) ? $field->value = $data['layouts_path'] : $field->value = "/site/templates/layouts");
		$wrapper->append($field);
		$field = new InputfieldText();
		$field->label = "Controllers path";
		$field->attr('name+id', 'controllers_path');
		if(isset($data['controllers_path']) ? $field->value = $data['controllers_path'] : $field->value = "/site/templates");
		$wrapper->append($field);
		$field = new InputfieldText();
		$field->label = "Snippets path";
		$field->attr('name+id', 'snippets_path');
		if(isset($data['snippets_path']) ? $field->value = $data['snippets_path'] : $field->value = "/site/templates/snippets");
		$wrapper->append($field);
		$field = new InputfieldText();
		$field->label = "Views path";
		$field->attr('name+id', 'views_path');
		if(isset($data['views_path']) ? $field->value = $data['views_path'] : $field->value = "/site/templates");
		$wrapper->append($field);
		$form->append($wrapper);
		$field = new InputfieldText();
		$field->label = "Assets path";
		$field->attr('name+id', 'assets_path');
		if(isset($data['assets_path']) ? $field->value = $data['assets_path'] : $field->value = "/site/templates/assets");
		$wrapper->append($field);
		$form->append($wrapper);
		return $form;
	}
	public function ___install(){
		
		$page = $this->pages->get('template=admin, name='.self::PAGE_NAME);
		if(!$page->id){
			$page = new Page();
			$page->template = $this->templates->get('admin');
			$page->parent = $this->pages->get($this->config->adminRootPageID);
			$page->name = self::PAGE_NAME;
			$page->title = 'MVC';
			$page->process = $this;
			$page->save();
		}
		$mvc_field = $this->fields->get('mvc');
		if(!$mvc_field->id){
			$mvc_field = new Field();
			$mvc_field->name = 'mvc';
			$mvc_field->label = 'MVC';
			$mvc_field->description = 'Checkbox that enables MVC for a page';
			$mvc_field->type = 'FieldtypeCheckbox';
			$mvc_field->save();
		}
		$mvc_register_field = $this->fields->get('mvc_register_page_id');
		if(!$mvc_register_field->id){
			$mvc_register_field = new Field();
			$mvc_register_field->name = 'mvc_register_page_id';
			$mvc_register_field->label = 'MVC Register Page ID';
			$mvc_register_field->description = 'Checkbox that enables MVC for a page';
			$mvc_register_field->type = 'FieldtypePage';
			$mvc_register_field->save();
		}
		if(!$this->templates->mvc_register){
			$t = new Template();
			$t->name = 'mvc_register';
			$fieldgroup = $this->fieldgroups->get($t->name);
			if(!$fieldgroup->id){
				$fieldgroup = new Fieldgroup();
				$fieldgroup->name = $t->name;
				$fieldgroup->add($this->fields->get('mvc_register_page_id'));
				$fieldgroup->save();
			}
			$t->fieldgroup = $fieldgroup;
			$t->roles = array($this->roles->get('superuser')->id);
			$t->save();
		}
		$permission = $this->permissions->get(self::PERMISSION_NAME);
		if(!$permission->id){
			$permission = new Permission();
			$permission->name = self::PERMISSION_NAME;
			$p->title = $this->_('Use the MVC module');
		}
		
	}

	public function ___uninstall(){
		$permission = $this->permissions->get(self::PERMISSION_NAME);
		if($permission->id){
			$permission->delete();
		}
		$page = $this->pages->get('template=admin, name='.self::PAGE_NAME);
		if($page->id){
			$page->delete();
		}
		$mvc_field = $this->fields->get('mvc');
		if($mvc_field->id){
			//$mvc_field->delete();
		}
		$mvc_register = $this->templates->get('mvc_register');
		if($mvc_register->id){
			//$mvc_register->delete();
		}
	}
	/*
		Methods for this view
	*/
	public function execute(){
		return $this->_renderIndex();
	}

	public function ___executenewController(){
		return $this->_rendernewController();
	}

	public function ___executeviewController(){
		return $this->_renderviewController();
	}

	public function ___executecreateView(){
		return $this->_rendercreateView();
	}
	/*
		Render methods for this view
	*/
	private function _renderIndex(){
		$this->setFuel('processHeadline', 'MVC | index');

		$controller_index = new InputfieldWrapper();
		$field = new InputfieldMarkup();
		$field->label = $this->_("Actions");
		$field->columnWidth = 100;
		$html = '<a class="button" href="newController">Create controller</a>';
		$field->attr('value',$html);
		$controller_index->append($field);
		$field = new InputfieldMarkup();
		$table = $this->modules->get("MarkupAdminDataTable"); 
		$table->setEncodeEntities(false);
		$header = array(
			$this->_x('Controller', 'list-thead'),
			$this->_x('Views', 'list-thead'));
		$table->headerRow($header);
		$field->label = $this->_("Controllers");
		$controller_html = "";
		foreach($this->templates as $t){
			if($t->fields->get('mvc')){
				$table->row(array('<a href="viewController?controller_name=' . $t->name . '">' . $t->name . '</a>', '0'));
			}
		}
		$field->attr('value', $table->render());
		$controller_index->append($field);
		return $controller_index->render();
	}

	private function _rendernewController(){
		$this->setFuel('processHeadline', 'MVC | index');
		if($_SERVER['REQUEST_METHOD'] == 'POST'){
			//TODO: add file/folder for the controller
			$html = "";
			$template_id = $this->sanitizer->selectorValue($this->input->post('template'));
			$template = $this->templates->get($template_id);
			$template->fields->add($this->fields->get('mvc'));
			$template->fields->save();
			$template->urlSegments = 1;
			$template->save();
			$path = $this->config->paths->templates . '/site/templates/';
			$wrapper = new InputfieldWrapper();
			$field = new InputfieldMarkup();
			$field->label = _('Added controller for') . " " .$template->name;
			$html .= _('Added MVC field to ' . $template->name) .'<br />';
			$html .= _('Allowed urlSegments for ' .$template->name) . '<br />';
			$html .= '';
			$field->attr('value', $html);
			$wrapper->append($field);
			return $wrapper->render();
		}else{
			$new_controller_form = new InputfieldForm();
			$new_controller_form->attr('method', 'post');
			$new_controller_form->attr('action', '');
			$controller_index = new InputfieldWrapper();
			$field = new InputfieldMarkup();
			$field->label = $this->_("Create new controller");
			$field->columnWidth = 100;
			$html = '<select name="template">';
			foreach($this->templates as $t){
				$html .= '<option value="' . $t->id . '">' . $t->name . '</option>';
			}
			$html .= '</select>';
			$field->attr('value',$html);
			$controller_index->append($field);
			$submit = new InputfieldSubmit();
			$submit->attr('class', 'button');
			$submit->attr('value', 'Create');
			$controller_index->append($submit);
			$new_controller_form->append($controller_index);
			return $new_controller_form->render();
		}
	}

	public function _renderviewController(){
		if(isset($this->input->get->controller_name)){
			$controller_name = ucfirst($this->sanitizer->text($this->input->get->controller_name)).'Controller';
			$controller_file = $this->sanitizer->text($this->input->get->controller_name);
			if(file_exists($this->config->paths->root. $this->controllers_path . "/" . $controller_file . '.php')){
				include($this->config->paths->root. $this->controllers_path . "/" . $controller_file . '.php');
				if(class_exists(ucfirst($controller_name))){
					$class = ucfirst($controller_name);
					$parent_methods = get_class_methods($class);
				    if($parent_class = get_parent_class($class)){
				        $diff_methods = get_class_methods($parent_class);
				        $child_methods = array_diff($parent_methods, $diff_methods);
				    }else{
				        $child_methods = $parent_methods;
				    }
				   	$table = $this->modules->get("MarkupAdminDataTable");
				    $header = array(
						$this->_x('View', 'list-thead'),
						$this->_x('File', 'list-thead'),
						$this->_x('Created', 'list-thead')
					);
					$table->headerRow($header);
				    foreach($child_methods as $view){
				    	$view_path = $this->config->paths->root . $this->views_path . "/" . ucfirst($controller_file) . '/' . $view . '.tmpl';
				    	if(file_exists($view_path)){
				    		$view_exists = 'View created';
				    	}else{
				    		$view_exists = 'View does not exists';
				    	}
				    	$table->row(array($view, $view.'.tmpl', $view_exists));
				    }
				    $wrapper = new InputfieldWrapper();
				    $field = new InputfieldMarkup();
				    $field->label = "Actions for " . $controller_name;
				    $field->attr('value', '<a href="createView?controller_name=' . $controller_name . '">Create view</a>');
				    $wrapper->append($field);
				    $field = new InputfieldMarkup();
				    $field->label = 'Views for ' . $controller_name;
				    $field->attr('value', $table->render());
				    $wrapper->append($field);
				    return $wrapper->render();

				}else{
					return 'Controller doesn\'t exist';
				}
			}else{
				return 'No controller file found for ' . $controller_name . " in " . $this->config->paths->root. $this->controllers_path;
			}
		}
	}

	private function _rendercreateView(){
		if($_SERVER['REQUEST_METHOD'] == 'POST'){
			$wrapper = new InputfieldWrapper();
			//TODO: create view here
			return $wrapper->render();
		}else{
			if(isset($this->input->get->controller_name)){
				$form = new InputfieldForm();
				$wrapper = new InputfieldWrapper();
				$field = new InputfieldMarkup();
				$field->label = "Create view";
				$view_name = new InputfieldText();
				$view_name->label = "View name:";
				$field->append($view_name);
				$wrapper->append($field);
				$field = new InputfieldSubmit();
				$field->attr('value', 'Create view');
				$wrapper->append($field);
				$form->append($wrapper);
				return $form->render();
			}else{
				return 'Error, no controller in $_GET';
			}
		}
	}

	public function create_mvc(){
		if($this->page->template->fields->get('mvc')){
			//MVC is enabled for this template and therefor page;
			if(isset($this->input->urlSegments[1]) ? $action = $this->input->urlSegments[1] : $action = 'index');
			$controller = $this->page->template->name;
			$controller_path = $this->config->paths->root . $this->controllers_path. "/" .$controller.'.php';
			if(file_exists($controller_path)){
				$controller_class = ucfirst($controller).'Controller';
				if(class_exists($controller_class)){
					$this->register_controller($controller, $this->page->url);
					$this->controller = new $controller_class();
					$this->set_action($action);
					$this->set_view_root(ucfirst($this->page->template->name));
					$rendered = $this->render();			
				}else{
					echo 'Class ' . $controller_class .' does not exist in ' .$controller_path;
				}
			}else{
				echo 'The file ' . $controller_path . ' does not exist';
			}
			if(isset($rendered)){
				echo $rendered;
			}
		}
	}
	/*
		Set the action for the controller
	*/
	public function set_action($action='index'){
		$this->action = $action;
	}

	public function set_view_root($view_root){
		$this->view_root = $view_root;
	}
	/*
		Sets the controllers layout to the default layout when left empty
	*/
	private function _set_controller_layout(){
		if($this->controller->layout === NULL){
			//Layout file is not set in the controller, we use the default layout file.
			$this->controller->layout = $this->default_layout;
		}
	}
	/*
		Sets the controllers view to the action.view if not specified
	*/
	private function _set_render_view(){
		if($this->controller->view === NULL){
			$this->controller->view = $this->action . '.tmpl';
		}	
	}
	/*
		Template engine
	*/
	private function _render_file_twig($path, $file, $vars){
		$this->loader = new Twig_Loader_Filesystem($path);
		$this->twig = new Twig_Environment($this->loader, array('debug' => true));
		$processwire_vars = array('user', 'pages', 'page', 'sanitizer', 'files', 'input', 'permissions', 'roles', 'templates', 'session', 'config', 'controller', 'wire');
		foreach($processwire_vars as $key => $pw_v){
			if(!isset($vars[$pw_v])){
				$vars[$pw_v] = $this->$pw_v;
			}
		}
		$this->twig->addGlobal('this', $this);
		$template = $this->twig->loadTemplate($file);
		return $template->render($vars);
	}
	/*
		Includes Layout file, extracts variables etc etc.
	*/
	public function render(){
		if(method_exists($this->controller, $this->action)){
			//We need to check if the method is used in the controller and not in the parents AppController and/or Controller
			$f = new ReflectionClass($this->controller);
			$methods = array();
			foreach($f->getMethods() as $m){
				if($m->name == $this->action){
					if($m->class == $this->controller){
						$this->controller->{$this->action}();
					}
				}
			}
			$this->view_body = $this->render_view();
		}else{
			$this->error->show('Method ' . $this->action . ' not found in  ' . $this->controller, $this->action, $this->controller);
		}
		$this->_set_render_view();
		$this->_set_controller_layout();
		if(!file_exists($this->config->paths->root . $this->layouts_path."/".$this->controller->layout)){
			$this->error->show('Layout not found', $this->action, $this->controller);
		}
		if(!file_exists($this->config->paths->root . $this->views_path.'/'. $this->view_root . "/" . $this->controller->view)){
			$this->error->show('View not found', $this->action, $this->controller);
		}
		$layout_content = file_get_contents($this->config->paths->root . $this->layouts_path."/".$this->controller->layout);
		$view_content = file_get_contents($this->config->paths->root . $this->views_path.'/'. $this->view_root . "/" . $this->controller->view);
		$bind_content = "{% extends \"layout.tmpl\" %} ";
		$templates = array();
		$bind_content .= '{% block view %}' . $view_content . " {% endblock %}";
		$templates['layout.tmpl'] = $layout_content;
		
		foreach($this->controller->snippets as $snippet_name => $snippet){
			if(!file_exists($this->config->paths->root.$this->snippets_path ."/" . $snippet)){
				$this->error->show('Snippet not found', $this->action, $this->controller);
			}
			$snippet_content = file_get_contents($this->config->paths->root.$this->snippets_path ."/" . $snippet);
			$bind_content .= "{% block ". $snippet_name . " %}" . $snippet_content . " {% endblock %}";
		}	
		$templates[$this->controller->view] = $bind_content;
		$loader = new Twig_Loader_Array($templates);
		$processwire_vars = array('user', 'pages', 'page', 'sanitizer', 'files', 'input', 'permissions', 'roles', 'templates', 'session', 'config', 'controller', 'wire');
		foreach($processwire_vars as $key => $pw_v){
			if(!isset($vars[$pw_v])){
				$vars[$pw_v] = $this->$pw_v;
			}
		}
		foreach($this->controller->vars as $key=>$val){
			$vars[$key] = $val;
		}
		$twig = new Twig_Environment($loader);
		$twig->addGlobal('this', $this);
		echo $twig->render($this->controller->view, $vars);
	}
	/*
		Render the layout
	*/
	public function render_layout(){
		$this->_set_controller_layout();
		if(file_exists($this->config->paths->root . $this->layouts_path."/".$this->controller->layout)){
			return $this->_render_file_twig($this->config->paths->root . $this->layouts_path, $this->controller->layout, $this->controller->layout_vars);
		}else{
			$this->error->show('Layout <b>' . $this->config->paths->root . $this->layouts_path."/".$this->controller->layout . '</b> not found!', $this->action, $this->controller);
		}
	}
	/*
		Render the view
	*/
	public function render_view(){
		$this->_set_render_view();
		if(file_exists($this->config->paths->root . $this->views_path.'/'. $this->view_root . "/" .$this->controller->view)){
			return $this->_render_file_twig($this->config->paths->root . $this->views_path.'/'. $this->view_root, $this->controller->view, $this->controller->vars);
		}else{
			$this->error->show('View <b>' .  $this->config->paths->root . $this->views_path.'/'. $this->view_root . "/" .$this->controller->view . '</b> not found!' , $this->action, $this->controller);
		}
	}
	/*
		Rener a snippet
	*/
	public function render_snippet($snippet=NULL, $vars=array()){
		if($snippet === NULL){
			$this->error->show('Snippet is NULL' , $this->action, $this->controller);
		}
		if(file_exists($this->config->paths->root . $this->snippets_path .'/'.$snippet)){
			return $this->_render_file_twig($this->config->paths->root.$this->snippets_path, $snippet, $vars);
			//include($this->config->paths->root . $this->snippets_path .'/'.$snippet);
		}else{
			$this->error->show('No snippet found' , $this->action, $this->controller);
		}
	}
	/*
		Render html headers
	*/
	public function render_headers(){
		ksort($this->controller->scripts);
		$html = '';
		foreach($this->controller->scripts as $key => $src){
			$html .= '<script type="text/javascript" src="' . $this->config->urls->root . $this->assets_path . '/scripts/' . $src .'"></script>' . "\n";
		}
		ksort($this->controller->styles);
		foreach($this->controller->styles as $key => $src){
			$html .= '<link rel="stylesheet" type="text/css" href=" ' .$this->config->urls->root . $this->assets_path . '/styles/' . $src .'"/>'. "\n";
		}
		return $html;
	}

	public function get_view_body(){
		return $this->view_body;
	}

	/*
		EXPERIMENTAL FROM HERE ON
	*/

	/*
		Register controller, a registered controller has a page with a field that links to the page that is used to be the controller, this will be used as a routing-table like 
		mechanism
	*/
	public function register_controller($controller_name, $page_url){
		$controller_registry = $this->pages->get("title=$controller_name, template=mvc_register");
		if($controller_registry->id){
			//controller has been registered, but is the url still the same?
			if($controller_registry->mvc_register_page_id->url == $this->page->url){
				//The url hasnt been changed	
			}else{
				//The url has been changed, we need to update the url

			}
		}else{
			//Controller hasnt been registered
			/*$controller_registry = new Page();
			$controller_registry->template = $this->templates->get('mvc_register');
			$controller_registry->parent = $this->pages->get("name=" . self::PAGE_NAME);
			$controller_registry->title = $controller_name;
			$controller_registry->name = $controller_name;
			$controller_registry->mvc_register_page_id = $this->pages->get("url=$page_url");
			$controller_registry->save();*/
		}
	}
}